name: Test Workflow

on:
  workflow-dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Greet user
        run: echo "Hello, ${{ github.event.inputs.name }}!"