name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Greet user
        run: echo "Hello, ${{ github.event.inputs.name }}!"