name: 02 - Workflow Events

on:
  - push:
      branches:
        - main
  - workflow_dispatch
  - schedule:
      - cron: '0 0 * * *'

jobs:
  check-event:
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Name
        run: echo "This workflow was triggered by the ${{ github.event_name }} event."
