name: 04 - Using Actions

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Dependencies
        working-directory: 04-using-actions/react-app
        run: npm ci
      - name: Run Unit Tests
        working-directory: 04-using-actions/react-app
        run: npm test
      