name: 05 - 2 - Event Filters and Activity Types

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Closed Event Type
        run: echo "This workflow was triggered by a pull request event of type '${{ github.event.action }}'."