name: 06 - Contexts

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'  

on: 
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        default: false
        type: boolean

jobs:  
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
            echo "Event name: ${{ github.event_name }}"
            echo "Ref: ${{ github.ref }}"
            echo "SHA: ${{ github.sha }}"
            echo "Actor: ${{ github.actor }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Run Number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: echo "The value of MY_VAR is ${{ vars.MY_VAR }}"
      - name: Print Env Variables
        env: 
          MY_STEP_VAR: 'step'
          MY_OVERWRITTEN_VAR: 'step'  
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR"
          echo "Overwritten env: $MY_OVERWRITTEN_VAR"
      - name: Print Env Variables
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR"
          echo "Overwritten env: $MY_OVERWRITTEN_VAR"