name: 07 - Using Expressions

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
    push:
      branches:
        - main
    workflow_dispatch:
        inputs:
          debug:
            description: 'Debug mode'
            type: boolean
            default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug}}
        run: |
            echo "Triggered by: ${{ github.event_name }}"
            echo "Branch name: ${{ github.ref }}"
            echo "Commit SHA: ${{ github.sha }}"
            echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ github.ref == 'refs/heads/main' && inputs.debug }}
        run: echo "I was triggered from main"
      - name: Greetings
        run: |
          echo "Hello, ${{ github.actor }}!"

