name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Build Status"
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      STATUS: ${{ steps.build.outputs.STATUS }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: echo "STATUS=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.STATUS == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying..."
